### ISSUE TITLE
warp cursor

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#11]
mouse pointer needs to be warped on MacOS 10.13.4. Maybe this is actually a devdraw issue.

**Comment by rjkroege** [comment]
The cursor is reliably warped on MacOS in regular Acme but right clicks continue to operate as if it was. And it is warped sometimes. So there is a devdraw issue. But there is also an edwood issue happening for me.

**Comment by paul-lalonde** [comment]
Pretty sure this is edwood - looks related to (not) catching the window-moved signal, somehow.

**Comment by rjkroege** [comment]
On 31 Mar 2018, at 6:26, Paul Lalonde wrote:

> Pretty sure this is edwood - looks related to (not) catching the 
> window-moved signal, somehow.

Seems like there are two possibilities?

* Edwood is failing to handle
* `9fans.net/go` is not delivering the right things from `devdraw`?

Maybe it’s worth attempting to divide in that way?

**Comment by paul-lalonde** [comment]
Turns out totally unrelated to the moved window.  Clobbering Expand.jump by accident.

**Comment by paul-lalonde** [comment]
Fixed in 37f298028e3bffe504d82f2fc17ace428035e401

**Comment by paul-lalonde** [comment]
fixed in 965232760efffe67c665efbb79e3eec904b2d382
