### ISSUE TITLE
Win doesn't work

### ISSUE THREAD

**Issue by paul-lalonde** [rjkroege/edwood#14]
Will do this next.  Can't do without.

**Comment by rjkroege** [comment]
yay!

**Comment by paul-lalonde** [comment]
See issue #19.

**Comment by paul-lalonde** [comment]
Looks like a race between tag updates from win and window resize from adding an error window.

**Comment by paul-lalonde** [comment]
Win works.  But frame keeps crapping out when adding too big a blob.  Not sure if it's frame or something else in the win path.

**Comment by paul-lalonde** [comment]
Fixed in 431fa70036cc1b9eabeb4d8fe695528f9905f389
Lots of events were broken.  Everything is still brittle as f*, but win now works.
