### ISSUE TITLE
Invalid Font arg locks the UI

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#16]
Attempt to activate an invalid Font (say by providing an argument to the `Font` command) and the UI will become permanently non-responsive.

**Comment by paul-lalonde** [comment]
Hmm, not reproducing here.  Does it happen in a fresh run?

**Comment by paul-lalonde** [comment]
[So, there's no way to fix a commit message reference to the wrong bug - it would change the hash and break Git ;-)  That was meant to be issue #15]

**Comment by paul-lalonde** [comment]
I've not been able to repro this at all.  Unless you've seen it again I'd like to close it.

**Comment by rjkroege** [comment]
This breaks running the tests on my computer. 😒

**Comment by paul-lalonde** [comment]
Without fontsrv running, I get nothing from 9p ls font; but devdraw should be picking up $PLAN9/font without fontsrv (though it won't show them in $NAMESPACE/font)
Currently, fonts are set to /lib/font/bit/lucsans/euro.8.font and /lib/font/bit/lucm/unicode.9.font; libdraw interprets the /lib/font/bin to point to #9/font, which it turns into just "font/", which implies devdraw is getting run from $PLAN9 on my system, at least.

**Comment by rjkroege** [comment]
Did you test on MacOS? And if you did, what rev of P9P do you have?

**Comment by rjkroege** [comment]
The problem only happens on high-dpi with bitmap fonts where `draw.scalesubfonts` is needed to produce the font. Fixed in PR https://github.com/9fans/go/pull/22.
