### ISSUE TITLE
paste to display: runes vs bytes

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#18]
Somewhere in the code stack between pasting a string and its display, there is a confusion about number of runes vs number of bytes. 

Replication: paste a string containing a multi-byte UTF8 rune repeatedly. Eventually see incorrect display updates. Contents of `Text` would appear to be correct as scrolling will fix the issue. I blame `frame`.

**Comment by paul-lalonde** [comment]
Might not be frame.  I've caught a couple in general acme code.  There seems to be no consistent way to know bytes vs runes, whether using string or []rune :-(

**Comment by rjkroege** [comment]
`string` everywhere for the win! Eventually.

**Comment by rjkroege** [comment]
I can't replicate this bug. I'll deem this fixed.
