### ISSUE TITLE
Frame is brittle

### ISSUE THREAD

**Issue by paul-lalonde** [rjkroege/edwood#19]
Something in win's setup is causing frame to freak out.  I think it's fr.Deleting a tag that has not yet been fr.Inserted, leading to bounds errors in box handling and messing up Nchars and Nlines.  And panics.  So many panics.
Frame probably wants to be robust to incorrect usage ;-)

**Comment by rjkroege** [comment]
Frame is scary. 😊 I'll work on this next. But can you describe replica states a little more precisely? 

It's not too hard to get Frame to panic so I'll work on making that happen less. 

* more unit tests for Frame (which will almost certainly drive some corrections)
* rationalizing `Insert`
* logging that shows why Frame's  gotten sad. In particular, how we ended up getting to this:

```
panic: frame.Insert pt1 too far
```

**Comment by rjkroege** [comment]
C `libframe` isn't particularly robust either. And Edwood's `Frame` is all of those issues plus whatever translation errors we've added.

**Comment by paul-lalonde** [comment]
Change cd69e4367fc678bed769e5318a5e397f945d47be clamps the linewraps to the frame.
It looks like much of the instability is caused by pt1.Y values coming back out of bounds from the line wrap, which just blindly adds font height to get the next line.  But that spills in many cases, and boom.
Clamping them has dramatically increased stability.

**Comment by rjkroege** [comment]
There's a larger problem with frame that I intend to fix: it assumes in a few places that the frame's `rect.Max.Y % FontHeight == 0`
