### ISSUE TITLE
moveing windows make cursor disappear

### ISSUE THREAD

**Issue by xxzozaxx** [rjkroege/edwood#194]
Hi,

when I  move windows form colume to another it make cursor disapear, 

info
OS: Debian Gnu/Linux with p9p
build command: go build
*EDIT 1:* more information
I use Ctrl Botton1 cuz in my laptop I don't have Botton2

**Comment by fhs** [comment]
I'm guessing this is related to the 32x32 cursor support that was added to devdraw few months back. Can you apply this patch and see if it fixes the issue: https://github.com/9fans/plan9port/pull/217 ?

Another mouse related fix you may want to apply is this: https://github.com/9fans/go/pull/6#discussion_r242792498

**Comment by xxzozaxx** [comment]
Thanks for fas respond @fhs .

sadly, I added your p9p patch and recopile it, and recompile edwood and **nothing happen**. I don't know what to do with your go patch as I don't know that repo (yet)

also I add more info, that I use Ctrl+Botton1 not Botton2 if that may help

**Comment by fhs** [comment]
Disappearing cursor most definitely means you're using the latest p9p devdraw without my 16x16 cursor fix. Make sure you're using the devdraw with the fix. You need to recompile libdraw and then recompile devdraw, or you can recompile everything.

(I hope to eventually remove all p9p dependencies from Edwood, so we don't have to deal with these kinds of issues.)

**Comment by xxzozaxx** [comment]
yup, Thanks it works now
