### ISSUE TITLE
dragging Windows up/down doesn't work

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#2]
It's not currently possible to drag `Window` objects up and down. (They can however be dragged between columns.)

**Comment by paul-lalonde** [comment]
Odd, it used to work :-)

**Comment by paul-lalonde** [comment]
frame/insert.go:217 is my least favourite line of code.  I can't tell if I'm mis-using Frame, or if it's mis-using me.

**Comment by rjkroege** [comment]
It's intermittently crash-y. This is a duplicate of #19

**Comment by paul-lalonde** [comment]
This turns out to be real, and fixed in b3032372be663724efceb0ef61030b2383842ec7
