### ISSUE TITLE
use box cursor

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#20]
I miss the box cursor while dragging windows. Add this.

**Comment by paul-lalonde** [comment]
Cursor handling is missing from 9fans.net/go/draw.

**Comment by rjkroege** [comment]
Vendoring a modified version was in my Todo list.

**Comment by paul-lalonde** [comment]
I have this working now, but with a patch upstreamed to 9fans/go/draw.
You may pull the patch from my branch into your 9fans branch:

    cd <asdf>/9fans/go
    git remote add flux https://github.com/paul-lalonde/go.git
    git fetch flux
    git merge flux/master

After that (or when upstream takes my pull request) I'll push.

**Comment by rjkroege** [comment]
Definitely fixed now. 😊
