### ISSUE TITLE
right-drag in win tag doesn't work as expected

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#23]
I right dragged a fraction of the win tag (the current working directory) and expected to get a directory opened. Nothing happened.

**Comment by rjkroege** [comment]
Right drag in `win` body doesn't work either. In particular (and most inconveniently) one can't open files by right-clicking on them like this.

**Comment by paul-lalonde** [comment]
Works with rooted paths, but not relative.  Awkward.  Fixing.

**Comment by paul-lalonde** [comment]
At least two bugs: DirName was building unrooted paths incorrectly (fixed); Look event forwarding (and back) seems broken.
