### ISSUE TITLE
B command doesn't open a file

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#24]
The B command failed to open anything.

Console output (possibly suspect) at roughly the same time:

```
9pserve: announce unix!/tmp/ns.rjkroege.:0/acme: Address already in use
acme: can't post service: 9pserve failed
```

**Comment by paul-lalonde** [comment]
No plumber support yet.  Will add that next.

**Comment by paul-lalonde** [comment]
8074242df5214bbd5c9037beb583734dfa03a226 adds rudimentary support.
But there's a bunch of caveats:
- the executable must be called acme
- It must open a socket called acme [as we do].  Calling it edwood breaks too much of the ecosystem.
- It must be on the path in the right spot for the plumber to see it.
The right way to proceed is probably to call our project acme.

**Comment by rjkroege** [comment]
The plumber already supports sam and acme via config file. It ought to be easily configured to use edwood. edwood definitely needs to mount itself as acme.

**Comment by rjkroege** [comment]
In particular, so long as edwood is in the path, then
```
9p read plumb/rules  | sed 's/acme/edwood/' | 9p write plumb/rules

**Comment by rjkroege** [comment]
will make B work. It broke my plumbing config in other ways though for reasons having nothing to do with edwood.

**Comment by rjkroege** [comment]
Some other plumbing stuff however requires fixing:
```
Unimplemented: main.plumbshow(0xc4203cb740): /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/look.go:252 +0x20
```

**Comment by paul-lalonde** [comment]
Yep.  Known still undone - there's a reason I didn't close this :-)

**Comment by paul-lalonde** [comment]
All working now, I think, as of d314d43ca2ea75f51dcb6d8384f875f7027d137f
