### ISSUE TITLE
sam command u doesn't redo

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#241]
According to the sam manual page, `u -1` should redo 1 previously undone edits. This doesn't work in Edwood. It doesn't work in Acme. It doesn't seem to work in p9p sam. There's code in `ecmd.go:/func.*u_cmd` to implement it. But we fail in the command parse for the `u` command.

**Comment by rjkroege** [comment]
Ah. The space in `u -1` is not accepted by the parser. Is this a bug or not?

**Comment by fhs** [comment]
There is a parser test for it at `edit_test.go:/u-3.*cmdc/`. 
The `s` command is the only other command that takes a count (e.g. `s2/x/y/`).
I think the documentation should be more clear that there should be no space.

**Comment by rjkroege** [comment]
I had found the parser test. Trying to parse with a space hangs the test. 😊. Anyway, this is obviously *working as intended*. I suppose that I could submit a change to the manual page in p9p.
