### ISSUE TITLE
Window name is not editable

### ISSUE THREAD

**Issue by fhs** [rjkroege/edwood#248]
Any text before the `|` in the tag is not editable. This is a regression: `git bisect` found commit fd9c3daf6a087f28e3e6fe1bdc90c4fe83aaf591 is the first bad commit.

**Comment by fhs** [comment]
To be more accurate, erasing (with backspace) and cut of the filename is not working. Insertion is working fine.

It seems to be caused by the `f.name != ""` condition in `File.SaveableAndDirty`. Since `w.tag.file.name` is always empty, `w.Commit(&w.tag)` never happens.

**Comment by rjkroege** [comment]
Yes. My fault.
