### ISSUE TITLE
ls isn't columnated

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#25]
ls output isn't columnated in win session.

**Comment by paul-lalonde** [comment]
It is for me.  Shell parameters weird?

**Comment by rjkroege** [comment]
conceivably. My shell is `$PLAN9/bin/rc` and `ls` uses the `$PLAN9/bin/mc` to columnate. `mc` reaches into the acme filesystem to discover the correct width of the column. So this is liable to be a filesystem bug?

**Comment by paul-lalonde** [comment]
Yes, that's very likely to be an interaction with fsys.  Mc outside of win fails to columnate correctly.

**Comment by paul-lalonde** [comment]
It's your change adding " " (%q instead of %s) around font names in Window.CltPrint.  mc expects it clean, and doesn't strip them.
I'd rather fix fontsrv to do the right thing with DPI fontnames than break compatibility here.

**Comment by rjkroege** [comment]
I'll fix then.
