### ISSUE TITLE
Switch to GitHub Actions for CI?

### ISSUE THREAD

**Issue by fhs** [rjkroege/edwood#293]
GitHub Action runs start up and finish much faster than Travis CI. We should consider switching to it.
Here is the setup in acme-lsp: https://github.com/fhs/acme-lsp/blob/91db24dd981550b4c777e988b86491ad4aa57e20/.github/workflows/test.yml

**Comment by rjkroege** [comment]
Interesting. I'll look into it.

**Comment by rjkroege** [comment]
Consider using [super linter](https://github.blog/2020-06-18-introducing-github-super-linter-one-linter-to-rule-them-all/)
