### ISSUE TITLE
Crash when typing tab in row or column tag

### ISSUE THREAD

**Issue by fhs** [rjkroege/edwood#297]
Typing tab or `^I` in the row or column tag causes a crash. It doesn't crash in p9p acme.
```
main.(*Text).Type(0xcf0978, 0x9)
	/home/fhs/go/pkg/mod/github.com/rjkroege/edwood@v0.2.1-0.20200119111631-42e89fa32346/text.go:861 +0xa94
main.(*Row).Type(0xcf0940, 0xc000000009, 0x12a, 0x8, 0x1)
	/home/fhs/go/pkg/mod/github.com/rjkroege/edwood@v0.2.1-0.20200119111631-42e89fa32346/row.go:284 +0x1e2
main.keyboardthread(0x9d04e0, 0xc0001960a8)
	/home/fhs/go/pkg/mod/github.com/rjkroege/edwood@v0.2.1-0.20200119111631-42e89fa32346/acme.go:484 +0x1ca
created by main.main.func2
	/home/fhs/go/pkg/mod/github.com/rjkroege/edwood@v0.2.1-0.20200119111631-42e89fa32346/acme.go:187 +0x832
```

**Comment by danieljamespost** [comment]
Interesting. This feature was merged in a couple of months ago and I haven't experienced this issue yet running on Linux (Debian). Is this specific to another OS?

**Comment by fhs** [comment]
I'm testing this on Arch Linux but you should be able to reproduce the issue on any OS, as long as the tab character reaches Edwood. You need to type tab in a *row* or *column* tag. It does not crash on a window tag.

**Comment by danieljamespost** [comment]
Ah I see. I can reproduce this issue as well.
