### ISSUE TITLE
Opening a directory generates copious spew

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#3]
Right-click on a directory. It opens in a Window. Yay! But also generates a great deal of unnecessary warning spew in `+Errors` for `stat` failures.

**Comment by rjkroege** [comment]
It's also the case that directory listings don't suffix directories with `/` characters to indicate that they're directories. I would expect that this may be related.

**Comment by paul-lalonde** [comment]
I don't see the missing suffix.  Which is to say, I see the /.  How are you making a slash-less directory?  I do see the spew, since earlier today.  Looking.

**Comment by rjkroege** [comment]
I right-clicked on a directory. And got the spew. And the newly open-ed directory's children did not have suffixes.

**Comment by paul-lalonde** [comment]
Fixed in commit 17a70bef01e7ea9fad49a01803d35b8be4f30c74
