### ISSUE TITLE
win fails for -tags mux9p set

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#314]
Edwood can use [fhs/mux](https://github.com/fhs/mux9p) with `go build -tags mux9p`. In this mode, While core Edwood functionality works as expected, `win` from p9p fails to operate correctly.

**Comment by fhs** [comment]
Note: this is due to `openfd(9)` 9P message that is used by plan9port to pass fd through unix domain socket. I added support for it in the last mux9p release, so it would work now if we update mux9p version in `go.mod` file.

**Comment by rjkroege** [comment]
Yay. I'd made a note to rev the version of fhs/mux in Edwood so will be able to fix this in a day or two.
