### ISSUE TITLE
Edit X/.*\.tex/D will loop on modified

### ISSUE THREAD

**Issue by paurea** [rjkroege/edwood#317]
Open one or more buffers.
Edit them.
Try to delete them with Edit using X will keep saying they are modified and
not delete them. Example (running the last line more than once will not delete the
buffers like in acme).

touch b.tex z.tex
B b.tex z.tex
Edit X/.*\.tex$/ , s/^/bla/
Edit X/.*\.tex$/D
Edit X/.*\.tex$/D

**Comment by paul-lalonde** [comment]
I'll look at this this week.
