### ISSUE TITLE
Remove window management?

### ISSUE THREAD

**Issue by fhs** [rjkroege/edwood#319]
I have an experimental fork which removes window management from Edwood here: https://github.com/fhs/edward
It felt like acme was trying to do too much. I'd rather leave window management to a separate window manager. I'm curious what others think about it.

**Comment by xxzozaxx** [comment]
So, I have a common feeling with that,

I like acme-ish way to manage windows (epically with mouse) that was there when wmii exist. now it more keyboard originated all over wms.

I considered fork [tabbed](https://tools.suckless.org/tabbed) to extend it to behave more like acme (in the way acme manage windows only) and make it more generalized. although I still believe that manage windows should only be wm job
