### ISSUE TITLE
pkg.go.dev: Documentation not displayed due to license restrictions.

### ISSUE THREAD

**Issue by camsn0w** [rjkroege/edwood#337]
It shows the license for edwood is a "Redistributable license" which is not one of the valid types listed on their site at: https://pkg.go.dev/license-policy without this the documentation for edwood cannot be shown. This can be seen at https://pkg.go.dev/github.com/rjkroege/edwood

**Comment by paul-lalonde** [comment]
@rjkroege How can I tell what code remains from Project Serenity?  I'd be happier to move away from GPL-3.

**Comment by paul-lalonde** [comment]
It also appears that the documentation shows fine, so I'll close this.

**Comment by rjkroege** [comment]
@paul-lalonde: I suppose that I could mine the Git logs for "this code came from Project Serenity" and then replace it with new Go code made out of the p9p C? Most of project serenity is in `frame` but I've altered that so much by now that I'm not sure how to proceed. Maybe I should just email the Project Serenity author and ask if he'd be OK with a different license?

**Comment by paul-lalonde** [comment]
That does sound like the easiest answer.

**Comment by rjkroege** [comment]
@paul-lalonde There is no GPL code in Edwood. It's under MIT and BSD-3. Do you still think that actions are required?

**Comment by paul-lalonde** [comment]
I'm going to claim travel-brain fog.  BSD-3 fine.  Must have cross read it
the other way.
Yes, no worries.  We can close this bug.

Paul
