### ISSUE TITLE
Vendoring

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#35]
Implement vendoring per [rsc's scheme](https://research.swtch.com/vgo-tour). Note that this will require building with `vgo`.

Why vendor: largely so that we can reuse / modify other packages. Like `9fans.net/go` in particular. But we might want to use some other packages as we extend/augment edwood.

**Comment by rjkroege** [comment]
I'm not convinced that the depot organization is necessarily right for vendoring. Hm.

**Comment by paul-lalonde** [comment]
As long as the plan9/go folks remain responsive, we should just keep it in place. 
You know the github trick where you make your own fork of the project an upstream in the original repo?

**Comment by rjkroege** [comment]
> On Apr 7, 2018, at 10:08, Paul Lalonde <notifications@github.com> wrote:
> 
> As long as the plan9/go folks remain responsive, we should just keep it in place.
> 
I uploaded a patch over a year ago and heard nothing. Maybe I did the uploading wrong. 

Also: Styled string support when We get there may not be upstreamable? 

> You know the github trick where you make your own fork of the project an upstream in the original repo?
> 
No. Please explain. 

BTW: rsc’s vendoring scheme works very well once I understood the way.

**Comment by paul-lalonde** [comment]
You fork the repo on Github, but download the original branch.  Add the forked repo as an upstream:
git remote add fork https://github.com/your/fork/here
Then you can pull/merge from your fork, as well as push to your fork to stage pull requests.

**Comment by rjkroege** [comment]
I'm thinking that this is fixed with Fazlul's #98 change.
