### ISSUE TITLE
Tag addition

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#37]
I have a script that adds some tag contents when I create a certain kind of file. The first string is not space separated from the default tag contents in Edwood vs Acme.

**Comment by paul-lalonde** [comment]
Screenshot please?

**Comment by rjkroege** [comment]
See the absence of space after `Edit`. In Acme, with the same script to create a file, there is a space before `mdpreview` with the same external program to add to the tag.

<img width="431" alt="edwood-tag" src="https://user-images.githubusercontent.com/749383/38467416-3b228592-3b06-11e8-8fe8-f1d367bc9737.png">

**Comment by paul-lalonde** [comment]
Fixed in 6c48d7fd0805b6baa0335b60da7fa16799d237c3
