### ISSUE TITLE
Backward search performance is terrible using :-/xxx

### ISSUE THREAD

**Issue by tiancaiamao** [rjkroege/edwood#398]
In acme, you can use right click on`:+/xxx` to search string `xxx`, it search from the forward direction. There is also a `:-/xxx` to seach from  the backward direction.

In acme, the backword search is basically the same with the forward search.
However, in edwood, `:-/xxx` is very slow,  an order of magnitude slower than `:+/xxx`

**Comment by paul-lalonde** [comment]
That's the golang regexp library vs the hand-coded one in acme.  This is
probably a strong enough argument to do regexp in edwood directly, though
that's at high engineering cost.

**Comment by rjkroege** [comment]
First duplicate bug! That's sort of exciting. We should fix this. Tracked in #301
