### ISSUE TITLE
can't select from top corner of some Text(s)

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#4]
I couldn't select starting from any rune on the first line in a `Text`. I presume that I am incorrectly computing the target rune from the mouse position. Investigate `Ptofchar` implementation. In particular: notion is to validate that the box model aligns correctly with the containing `Frame` rectangle.

**Comment by paul-lalonde** [comment]
I'm not reproducing this at head.  I suspect the fix for tag Nlines fixed this as well.

**Comment by rjkroege** [comment]
I can't get it to happen anymore.
