### ISSUE TITLE
relocating a Window between columns redraws strangely

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#40]
I drag (well, move I suppose) a Window from a larger to smaller column and it

* doesn't draw right in the new smaller column at first. (Indented lines were missing?) 
* but (here's the odd part) the area in the original column became a "zombie" Window (the Window was relocated to the smaller column)
* resizing fixed all

**Comment by rjkroege** [comment]
I think this might be a frame bug.

**Comment by paul-lalonde** [comment]
Could be frame, but I don't think so - the window code move code does a clear, IIRC, so I'm guessing there's a path that's missing the redraw part of the dragging code.  I've replicated this within one column by "shuffling" a window back and forth.  I'm also getting bad layouts doing where the tags all collapse together.  I'll walk the layout code.

**Comment by paul-lalonde** [comment]
Found it.  Had lost the invariant that windows within column are sorted by Y in their array.  Fixed in 0f7ff9d
