### ISSUE TITLE
Edit still working oddly?

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#42]
I keep on trying things with Edit and being surprised compared to Acme.

* `Edit x/^/ i://:` to comment out a selection. Or not? I must have misunderstood.
* `Edit x://: d` to remove the comments? `ssam` did the right thing with this command with the exception of inserting 4 invalid rune characters at the end of the selection. (Is that Edwood or `ssam`? Edwood also left the selection in a bad state for which we can see #30.
* `Edit ,x/\(image\.Point, image\.Point\)/ c/(image.Point, image.Point, *Frame)/` did something odd. `ssam` worked as expected (except for more invalid runes at the end of the buffer.)

@fluxlalonde: I thought that you had fixed the first one?

**Comment by paul-lalonde** [comment]
The first works for me at top-of-tree.  What are you seeing?
The second "works" but appears to require re-painting; I'll see if I can find the problem.
4 invalid runes at the end of selection may well be an edwood bug - I am probably missing a reslice after importing text from the external command on that path.  I'll look for it.
I'll worry about the last when I I have the other two cleared up.

**Comment by rjkroege** [comment]
The first one only inserted the comment on the first line of the selection. Not every line in the selection.

**Comment by paul-lalonde** [comment]
I'll call that right odd - it's been solid for me here.  Let's see if we can poke at it live later today - I'd like to reproduce it in my setup.

**Comment by rjkroege** [comment]
As of cc82b34691e2657ceb6594d439096ffa104b46e1, this bug does not replicate and all the Edit commands that I attempted work as expected.
