### ISSUE TITLE
Broken frame insertion since #436 

### ISSUE THREAD

**Issue by dnjp** [rjkroege/edwood#438]
I need to read up on the recent changes to buffer and frame handling to understand what is going on, but it appears that #436 broke frame insertion. Here's a screen recording showing the difference between https://github.com/rjkroege/edwood/commit/9637ebff7edb47c3ea22dbc5938df49e9cb8b0ab and https://github.com/rjkroege/edwood/commit/6ebb3f3b3e823c8a21ad5483a5df3730e716c869:

https://vimeo.com/682276362/a2114cf8ae

**Comment by rjkroege** [comment]
Oops. I think that your PR #439 would fix this? Thanks for the patch. I want to try something with #439 to make sure that it fits with what I want to do to `frame`.

**Comment by dnjp** [comment]
Sounds good. Let me know if anything in #439 needs to change based on what you have planned.
