### ISSUE TITLE
how do I configure plumb rule on window system

### ISSUE THREAD

**Issue by ianzhang366** [rjkroege/edwood#452]
Hi there,

I'm new to `edwood`, it's a great project, thanks for your work.

I'm trying to figure out how to set up the plumber and plumb rule with my `edwood`.

As on plan9, I can used `cat rules.txt | 9p write plumb/rules`, but not sure how to do this on Windows 11.

Can you please give me some direction for this?

**Comment by rjkroege** [comment]
I don't know how to run the `plumber` on Windows. @camsn0w has told me that parts of Plan9Port will work in the Windows Linux subsystem. Maybe you could use that? With a working `plumber`, the above would work. (Your approach works on Linux and MacOS.)

**Comment by ianzhang366** [comment]
I see, thanks!

I wonder how does the `Button Three` work for `edwood`,

From `http://acme.cat-v.org/mouse`, it says, `Button Three - Plumb, if plumb fails, search for next occurrence of text*.`.
If we don't run `plumber` on Windows, how do we implement this?

Also do you we have any doc that shows how to set up https://github.com/fhs/acme-lsp with `edwood`?

**Comment by ianzhang366** [comment]
Hi @camsn0w  do you have any doc that I can follow up for using the `plumber` with WSL, then I can feed it to `edwood`

**Comment by rjkroege** [comment]
> how does the Button Three work for edwood

There's a default implementation of the right button. Look at `look3()` if the plumber isn't working.

> Also do you we have any doc that shows how to set up https://github.com/fhs/acme-lsp with edwood?

I don't. I mean to get around to setting it up. @fhs has some reasonable getting started info at the link that you shared. Maybe try it out and see how it works. If you make some notes, please add them here as a PR.

**Comment by camsn0w** [comment]
> Hi @camsn0w do you have any doc that I can follow up for using the `plumber` with WSL, then I can feed it to `edwood`

Have you tried installing WSL and installing edwood on it and running it over the new windows xserver? That seems like the most painless way to do it.

**Comment by paul-lalonde** [comment]
I've been using it - it runs pretty much out of the box.  Issue the
acme-lsp command from within a win (or middle-click) with the parameters
pointing at the source code you want it to see.
You'll need all the little "L" scripts accessible.
