### ISSUE TITLE
HTML link selections

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#46]
Currently Edwood doesn't support the HTML selection constructs that Acme offers. This is inconvenient while editing HTML.

**Comment by paul-lalonde** [comment]
This is another example of something I'd like to externalize - it doesn't really fit the structure of acme very well. I'll look at what it would take to plumb the look clicks through a tool instead of hard-coding selection boundaries.

**Comment by paul-lalonde** [comment]
Implemented in a884301324332dbb964823999cc1b56dae175a88

**Comment by rjkroege** [comment]
I agree that it would be nice to externalize custom custom selection processing.
