### ISSUE TITLE
fatal error in Buffer.undone reading inserted contents: EOF

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#471]
Fatal crash. Not nice. Replicate:

* create a buffer with `New`
* paste a bunch of text
* Do a large `Edit` op
* `Undo`

**Comment by rjkroege** [comment]
@camsn0w did you ever see this?

**Comment by rjkroege** [comment]
Seems to be on the *first* delta. The second change is correctly undoable. It also seems to require the use of `Edit`.

**Comment by paul-lalonde** [comment]
This looks like a duplicate of #467, with a bit more repro context.

**Comment by rjkroege** [comment]
Yes. Definitely #467.
