### ISSUE TITLE
Windows filename handling is utterly broken.

### ISSUE THREAD

**Issue by paul-lalonde** [rjkroege/edwood#472]
Edwood (nor acme) cannot handle driver letters and backwards slashes in path names.
I believe we use Path internally in some places to handle paths, but not everywhere.  We should probably use package path everywhere we parse paths/guess at filenames.  Button 3/Look would benefit greatly.  This would almost make edwood usable on Windows.

**Comment by rjkroege** [comment]
That code needs some more attention. More refactoring. Maybe I'll have time soon.

**Comment by rjkroege** [comment]
Meta comment: the tag contents are both editable text and "structured" in that Edwood *parses* the tag. This is special cased throughout the code in convoluted ways. My design intuition is that the "right way" to address this is to provide some kind of parse tree layer adjacent to a `file.Buffer`.

I can't yet decide if I want to make fixing this contingent on refactoring the handling of "structured" text in Edwood.

@paul-lalonde given that I don't have a windows device conveniently at hand, are there some low-road concrete fixes that might be the 20% that addresses 80% of your unhappiness?

**Comment by rjkroege** [comment]
Probably helped with #483.

**Comment by paul-lalonde** [comment]
Yes, I think handling spaces is the 80% fix that makes it usable.  Handling
drive prefixes and backslashes would finish it.  Drive prefix handling is
ugly because of single character filenames followed by an address, so I
suspect windows edwood will need knowledge of currently mounted drive
letters.  And to do that right you need notifications of mount/unmount
events, or a test for a letter being a drive.  The latter is simpler, but I
don't know if it will be fast enough.
Paul

**Comment by paul-lalonde** [comment]
Fixed in #485
