### ISSUE TITLE
Windows build doesn't draw into window?

### ISSUE THREAD

**Issue by paul-lalonde** [rjkroege/edwood#484]
I'm likely misconfigured, but I don't see anything in our documentation.
I launch edwood at the command line, it tells me it has a 9P fileserver listening, opens a windows, but it remains gray. 
Any clues?
Windows 10 Enterprise 20H2, no WSL.

**Comment by rjkroege** [comment]
I thought that windows required building with `duitdraw` if you were going to run without WSL

**Comment by paul-lalonde** [comment]
Ok, tried `go build -tags duitdraw .`; no joy.  Running without WSL would make my life immensely easier.  We seem to lack actual Windows documentation.

**Comment by rjkroege** [comment]
@fhs any helpful comments on Windows usage?

I suppose that I'll get around to getting a Windows device up eventually.

**Comment by paul-lalonde** [comment]
I updated my wsl (I don't understand why that matters for duitdraw); upgraded my windows box to 2020 2H22, and I now have something that sort-of works. The initial refresh can be *very* slow - like 60-120 seconds.  After that the main elements work.  Filename handling is still fundamentally broken, so working on that now as time allows.

**Comment by fhs** [comment]
The duitdraw backend seems to work fine on x11. I haven't used edwood on Windows for some time. You may want to update some dependencies and see if that help, although I don't see any significant changes in `duitdraw` or `golang.org/x/exp/shiny`.

**Comment by paul-lalonde** [comment]
The problem appears to be at my end: it looks likesome awful corp anti-virus is doing a ridiculously lengthy scan of my executables, leading to minute-long startup delays for windows.  Closing.
