### ISSUE TITLE
Event file writes sometimes have Location in Arg

### ISSUE THREAD

**Issue by paul-lalonde** [rjkroege/edwood#487]
We can get:
"C1:M C2:x Q0:48 Q1:52 OQ0:49 OQ1:49 Flag:11 Text:Look Arg:/Users/flux/dev/edwood/cmd/win/win Loc:/Users/flux/dev/edwood/cmd/win/+win:#117,#120"

instead of
"C1:M C2:x Q0:48 Q1:52 OQ0:49 OQ1:49 Flag:11 Text:Look Arg:/Users/flux/dev/edwood/cmd/win/+win:#117,#120" Loc:/Users/flux/dev/edwood/cmd/win/+win:#117,#120"

Working on a reliable repro - this showed up cleanly (and repeatably) while working on win.

**Comment by rjkroege** [comment]
I'm already planning on looking at some of this code for #470 so I'll take this.

**Comment by paul-lalonde** [comment]
I believe I've found the cause - the a and aa variables returned from
getargs() in Execute() appear to be reversed.  I haven't finished tracing
it though well enough to be happy to commit the change.
There's another bug between here and the golang win that's causing the
"Send" to show up when chording it.  Still digging.

Paul
