### ISSUE TITLE
Cursor disappeared, clicks still delivered

### ISSUE THREAD

**Issue by paul-lalonde** [rjkroege/edwood#493]
Under Ubuntu with Wayland.  Cursor re-appears when past the edge of the window.
Might be a devdraw problem, or a dropped cursor event.

Recording this to have a place to log further occurences.

**Comment by paul-lalonde** [comment]
Does not happen when using duitdraw (though redraws are significantly slower?)

**Comment by paul-lalonde** [comment]
And it seems to be related to cursor warping being broken as well.

**Comment by 9garcia** [comment]
https://github.com/9fans/plan9port/pull/525 & https://github.com/9fans/plan9port/pull/550 are both wayland patches to devdraw. 550 seems to have cursor warping working with . An updated version of 525 can be found in 9front's drawterm https://github.com/9front/drawterm/tree/front/gui-wl.

**Comment by sfyatee** [comment]
> And it seems to be related to cursor warping being broken as well. Which appears to be a wayland limitation. Goodbye wayland.

I have finally switched to wayland and found that this branch (https://github.com/eaburns/plan9port/tree/wayland) works well. Tested it with edwood and plan9port's acme. Cursor warping works. To get things working I had to manually set DISPLAY=0 because wayland doesn't use that.

**Comment by paul-lalonde** [comment]
Thanks - I'll give it a spin.
