### ISSUE TITLE
column drawing blackness

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#52]
When creating many Windows (e.g. `B *.go`) and then attempting to manipulate Windows, we get black regions. 

![bug1](https://user-images.githubusercontent.com/749383/39632381-ec4e096e-4f82-11e8-9430-c31c2d4cb1a0.png)

The presence of the thin black rectangle in the margin shows that new content is being added with `Frame.Insert` but that `Text.Redraw` has not been invoked to fill the entire padded rectangle.

I think this might be a problem in the column code?

**Comment by rjkroege** [comment]
I'll add in passing that Edwood is *much worse* than Acme when handling columns with many Windows.

**Comment by paul-lalonde** [comment]
Agreed - I'll look for this one next time I have a few minutes; exec review this week killed my last couple of weeks of recreational programming.

**Comment by paul-lalonde** [comment]
Ok, at least one issue is in the interface change to Frame - The original colgrow function makes a few calls to to explicitly set Maxlines of a window.  How do I explicitly set Maxlines?  I don't see it in the frame interface.

**Comment by paul-lalonde** [comment]
More close reading leads me to believe that all the tag handling stuff is broken.  This will likely mean re-doing the layout logic to use the column and window rects instead of line counts.

**Comment by rjkroege** [comment]
I made the interface as small as possible without (hopefully) breaking anything.  You could call `frame.Init` with a `image.Rectangle` that's `new_maxlines * frame.DefaultFontHeight()` high?

Maybe that's a bad idea.

**Comment by rjkroege** [comment]
Aside: I'll probably want to get rid of `DefaultFontHeight` as part of handling multiple text styles.

**Comment by paul-lalonde** [comment]
Probably also need to abstract the "chrome" around windows a little better as well.  Too many (Border * ScaleSize) when they are all really used to calculate pixel heights of a window, or width of a column.

**Comment by rjkroege** [comment]
I have several comments / questions. 

First, I  went to write `MaxPixelHeight` and apparently don't understand what you're looking for because wouldn't it `Rect().Y` serve? That's the height of the `Frame`. 

Second, the (scaled) border issues: there's a some kind of "insets" widget property that would seem to have only an ad hoc implementation in Edwood? Maybe we need to separate the idea of structuring and layout from the mechanics of event handling and draw? 

Third: the way that `Frame` leaves `Rect().Y % DefaultFontHeight()` at the bottom of `Rect()` empty grates on me. Moreover, the code sometimes conflates this "fringe" with "insets".

**Comment by paul-lalonde** [comment]
The difference between MaxPixelHeight and Rect().Y is exactly Rect().Y %
DefaultFontHeight().  Today MaxPixelHeight would be DefaultFontHeight() *
MaxLines, but since you want to have variable line heights, I'd need
MaxPixelHeight to get the "correct" size for the window, to make windows
have integral numbers of lines, which we should strive for in layout.

**Comment by rjkroege** [comment]
First: I'm happy to add an accessor. It's `GetFrameFillStatus().MaxPixelHeight`

But second (and possibly irrelevant), if line heights are variable, layout should probably always just try to make the `Frame` an integral number of lines in the default font for the `Frame`?

**Comment by paul-lalonde** [comment]
I guess the issue is that if line height is variable I need a function that
Frame, knowing the current text, can return to me the actual height of text
given a frame height.  Does that make more sense?

**Comment by rjkroege** [comment]
Oh indeed that makes much more sense. I'll write that too. This will be cool!

**Comment by rjkroege** [comment]
I added a `TextOccupiedHeight` function that does what you need I think.

**Comment by paul-lalonde** [comment]
Close.  Can I have "TextOccupiedHeight(r image.Rectange) int" instead?  I'd like to pass it a tentative box, and get back what the height would be for that box.  
In the Column.Grow(), a new size is obtained for the window being expanded, and the difference is spread to the other windows; this involves shortening them, and I'd like to be able to shorten them exactly, rather than to an approximate line height - ie, always shorten to an actual like boundary.  So I need to know what the occupied height is for a smaller window rectangle, rather than of the entire current text.

**Comment by rjkroege** [comment]
Yes. I'll write this tomorrow.

**Comment by rjkroege** [comment]
Function enhanced per above.

**Comment by paul-lalonde** [comment]
Sorry, I haven't had the time to poke at this.  It's as if I can only write recreational code in the winter.

**Comment by rjkroege** [comment]
No problem. I'll have a look then.
