### ISSUE TITLE
Edit failure

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#55]
The following `Edit x/^/ i/<literal tab>/` does several things wrong.

* it inserts a single white space instead of a ta
* (incorrectly) draws the selection afterwards over all the space from the last character in the line to the edge of the Frame rectangle

Compare this behaviour with `|ssam 'x/^/ i/<literal tab>/'` which does replace the selected text. (Though there are still bugs with selection redrawing.)

**Comment by rjkroege** [comment]
Since f1c3688a27de4902919c6e73232b9c993cf6b522, the selection bug is much improved and only a valid character is selected. (Conceivably, the selection should be preserved? I need to check on what Acme does.)

However, both literal tabs and spaces cannot be inserted. What's the deal with spaces?

**Comment by paul-lalonde** [comment]
It's probably time to stop trying to use golang regexp and port Russ's acme regexp.  It's just different enough.

**Comment by rjkroege** [comment]
Perhaps. But that's not what was happening here. 😊

**Comment by paul-lalonde** [comment]
Well that was just embarrassing 😳
