### ISSUE TITLE
additional locks needed in window

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#57]
While `frame.Frame` is now thread-safe, other parts of Edwood are not. In particular, there is an easy-to-replicate problem:

* Start a child process that continuously generates output. I used `yes`.
* Move the `Window` to a different column.
* See crash:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x168 pc=0x117f805]

goroutine 50 [running]:
main.(*Window).SetTag(0xc420073800)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/wind.go:461 +0x75
main.xfidwrite.func1()
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/xfid.go:487 +0x20c
main.xfidwrite(0xc4202e8000)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/xfid.go:501 +0x438
main.xfidctl(0xc4202e8000, 0xc4200b80c0)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/xfid.go:46 +0x87
created by main.xfidallocthread
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/acme.go:628 +0x1e5
```

Conceivably, `Window` needs to be thread-safe?

**Comment by fhs** [comment]
The race detector reveals many data races, although some of them are due to `9fans.net/go/draw`. I won't paste the long output from `go test -race`.

**Comment by rjkroege** [comment]
We should definitely get to doing this. I suspect that I'd be horrified. How we restructure the code to resolve the races is however not obvious to me. Or perhaps more precisely, there are so many design choices that I can't decide.
