### ISSUE TITLE
Compile for 32 bits issue

### ISSUE THREAD

**Issue by dipoll** [rjkroege/edwood#60]
Got an error when tired to cross compile edwood for raspberry:

GOARCH=arm; GOOS=linux; go install github.com/rjkroege/edwood

./text.go:95:8: constant 9223372036854775807 overflows int

Looks like math.MaxInt64 should be changed for 
const MaxInt = int(^uint(0) >> 1)

Regards,

Dmytro

**Comment by rjkroege** [comment]
Oh dear. Thanks for filing.
