### ISSUE TITLE
gofmt and testing

### ISSUE THREAD

**Issue by fhs** [rjkroege/edwood#64]
Some of the files have not been run through gofmt. Enabling automatic testing with something like [Travis CI](https://travis-ci.org/) may be helpful here. Also, the tests should not require running `go build` before running `go test`, and they should not require a $DISPLAY being available.

**Comment by rjkroege** [comment]
Indeed.

**Comment by rjkroege** [comment]
BTW: if you have PRs for this, please send them to us.

**Comment by fhs** [comment]
To get rid of dependency on a display, we can use Xvfb but it's seems to be slow and not very portable. I think a better solution is to create a fake devdraw and set $DEVDRAW to that. Unless there is an easier solution, I'll look into devdraw.

I actually have a testing related PR waiting (#63) and two other PRs.

**Comment by rjkroege** [comment]
Conveniently I have been writing a [fake devdraw](https://github.com/rjkroege/devdraw) with the goal of providing a mechanism to test apps that use devdraw and ensure that they are emitting the correct draw calls. I had intended to use a modified version of that code to permit running Edwood easily under Travis and to let the tests run on any Go-supported platform.

**Comment by sbinet** [comment]
I commented directly on the PR, but let me post it there also:
- https://github.com/ktye/duitdraw/blob/master/README.md
(a `devdraw` implementation on top of `exp/shiny`.)

**Comment by rjkroege** [comment]
Doh. Obviously I need a working version of `devdraw`

**Comment by fhs** [comment]
`devdraw` and `9pserve` are the only two binaries you need from plan9port. I'd just host the binaries somewhere on github rather than compile p9p for every build.

**Comment by rjkroege** [comment]
Excellent suggestion. I had in fact decided on the same solution after noting my foolishness above. 😊

**Comment by rjkroege** [comment]
I suppose the one remaining issue is to enforce that `gofmt` is up to date.

**Comment by rjkroege** [comment]
All done. And hopefully setup to keep it clean.

**Comment by fhs** [comment]
Thanks!

**Comment by rjkroege** [comment]
Now if only there was more test coverage... 😊
