### ISSUE TITLE
|cmd execution doesn't work multiple times

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#7]
The first time that I middle-executed `|fmt` on a selection, all was well. The second and subsequent times, the selection was deleted and the stdout of `fmt` was dropped on the floor with the following warning:

```
Failed to open 4/rdsel: already in use
```

**Comment by paul-lalonde** [comment]
Fixed in ea53b04a2d4a3435f713e3909226571fa66bd6f9
