### ISSUE TITLE
file modification comparison for Put is odd

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#8]
Put always fails on the first click with a time comparison failure.

**Comment by paul-lalonde** [comment]
Expected: solution is to implement the sha1 calculation of the buffer correctly.

**Comment by paul-lalonde** [comment]
[Get shows how to do it, IIRC]

**Comment by rjkroege** [comment]
I have a temporary workaround.

**Comment by rjkroege** [comment]
Mitigated in 4b14327ed8884b533a09864f8aed17542c505dd3

**Comment by paul-lalonde** [comment]
Added hashing in 18619f5a5c2d2b3160355ab6924854bb3a47c127
