### ISSUE TITLE
Idiomatic text buffers

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#97]
Edwood could stand to have a new and improved text storage system. We've talked about various notions. A piece table with deltas would seem to be the most reasonable choice.

**Comment by mibk** [comment]
Not sure that would be a good fit for Edwood, but years ago I came across a vim-like editor called [vis](https://github.com/martanne/vis). Its [text management](https://github.com/martanne/vis/wiki/Text-management-using-a-piece-chain) system was based on the [Project Oberon](https://www.inf.ethz.ch/personal/wirth/ProjectOberon/) *(the introduction blog post: http://www.brain-dump.org/blog/entry/144/vis_a_highly_efficient_vim_like_text_editor)*. I ported (and then slightly changed the API) the text management part of the editor into the [package undo](https://godoc.org/github.com/mibk/syd/undo).

**Comment by rjkroege** [comment]
Thanks. This sounds promising. I'll take a look at your undo package.

**Comment by rjkroege** [comment]
# Strings vs Runes

* The Undo package operates on byte buffers.
* Edwood's `Buffer` object is an array of `rune`. 
* Using Undo would therefore entail a choice: switch Edwood to using utf-8 buffers (or strings) or modify Undo to use rune.

I somewhat prefer switching Edwood to utf-8 buffers if only because for most workloads it will greatly the heap space used for various text buffers by nearly a factor of 4.

This however seems like a somewhat far-reaching alteration. Many access patterns to `Buffer` iterate (e.g. `ReadC` loops in `text.go` or `addr.go`.) But sam addressing can be to a specific character.

@fhs Do you have an opinion on this?

# Sequencing
It's not obvious to me how to sequence this work. I have several incomplete CLs that attempt to make progress on this task per comment above and none of them seem to necessarily move forward. I think the primary first task it to make sure that all Edwood code outside of `File` stops depending on its internal details around dirty tracking.

**Comment by fhs** [comment]
Switching to UTF-8 buffers does seem nicer, but the problem is sam addressing. Maybe we can use [golang.org/x/exp/utf8string](https://godoc.org/golang.org/x/exp/utf8string) to efficiently index strings by rune. Given how much work is involved to switch to utf8 buffer, I think for now, we can just pick a Buffer implementation that works on runes, write some benchmarks, and call it a day. After Edwood has more test coverage and easier to refactor, we can come back to this problem.

The Buffer implementation should probably be moved into an internal package. It should also return errors for invalid index instead of panic, which will make it easier to test.

**Comment by rjkroege** [comment]
Update on this work: I want to relocate `File` into a separate module so that its public interface becomes obvious. This will permit writing unit tests that exercise the public interface that would (ideally) not be fragile across replacing the `File` implementation.

**Comment by rjkroege** [comment]
@camsn0w I was thinking to assign this to you. WDYT? 😀

**Comment by rjkroege** [comment]
Some additional thoughts about this work based on a discussion with @camsn0w and my pre-existing notes:

* `Buffer` has a confusing name. See #328.
* `undo.Buffer` is a subset of `File` in Edwood.
* `File` itself conflates some functionality: editable text buffers, observer pattern, the on-disk file that may back the text buffer. i.e. `File` is only sometimes backed by a... file.
* `File` uses `RuneArray` (new name of the current `Buffer`)
* `undo.Buffer` corresponds to the *editable text buffer* part of `File`

Conclusion: starting point is to refactor `File` into types reflecting these separate concepts:
* a text buffer with undo. (Operating assumption: implement this with `undo.Buffer` supplemented with some kind of appropriate rune cache.)
* a (strawperson name) `TextBufferAdapter`. `Text` has-a `TextBufferAdapter` and it maintains the list of `Text` instances that changes to the text buffer (e.g. on an undo etc.) will notify.
* a (strawperson name) `FileBufferAdapter `. `Text` also has a `FileBufferAdapter`. This type (interface?) maintains the connection between the text buffer and its providence: file on disk or directory listing etc. (Perhaps this could generalize some of the code for the `+Error` buffers?)

**Comment by rjkroege** [comment]
Some other notes in no particular order:

* re-factoring `File` will require doing something reasonable with the `Elog`. Maybe this could use the observer pattern (e.g. like the `TextBufferAdapter`) too?
* maybe pass in the `Elog` from `editcmd` instead of having it as state?
* `curtext` too. `editcmd` needs this concept but keeping it around as a global makes it hard to write nice unit tests sometimes.

**Comment by camsn0w** [comment]
Following a discussion with @rjkroege the current game plan here is as follows:
- Work on naming conventions and refactor
- Separate the observer pattern from the file struct
- Do the same for name and info
- Push file and buffer (rune_array.go) into their own package, with decent names and put them into a subdirectory
- Refactor for undo
- Modify undo

**Comment by rjkroege** [comment]
As of #430, Edwood is operating with the new-type utf8 byte buffers. Exciting! Thanks everybody who helped with the implementation. This unlocks many possible code improvements.

**Comment by rjkroege** [comment]
When should I consider this done? We now have new type buffers. But I've not finished taking advantage of them to improve Edwood operation. I'm going to declare this finished. Yay! 😀
